#!/bin/bash

function mypy {
    DEV=yes docker compose -f docker-compose-runner.yml run --rm orcidlink scripts/run-mypy.sh
}

function test {
  KBASE_ENDPOINT=ENDPOINT_TEST \
  ORCID_CLIENT_ID=ORCID_CLIENT_ID_TEST \
  ORCID_CLIENT_SECRET=ORCID_CLIENT_SECRET_TEST \
  MONGO_HOST=mongo \
  MONGO_PORT=27017 \
  MONGO_DATABASE=orcidlink \
  MONGO_USERNAME=dev \
  MONGO_PASSWORD=d3v \
  docker compose -f docker-compose-testing.yml run --rm orcidlink scripts/run-tests.sh ${1}
}

function black {
  DEV=yes docker compose -f docker-compose-runner.yml run --rm orcidlink scripts/run-black.sh ${1} ${2}
}

function help {
    echo "$0 <task> <args>"
    echo "Runs the tasks listed below."
    echo "To find out more about them, either read the source"
    echo "for ${0} or the docs located in 'docs/tasks.md'."
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}