KBASE_ENDPOINT=ci.kbase.us \
KBASE_SECURE_CONFIG_PARAM_ORCID_CLIENT_ID=APP-RC3PM3KSMMV3GKWS \
KBASE_SECURE_CONFIG_PARAM_ORCID_CLIENT_SECRET=5d599bcb-8d09-4888-acc9-26f2e8e0e51f \
KBASE_SECURE_CONFIG_PARAM_IS_DYNAMIC_SERVICE=yes \
DEV=yes \
docker compose up