KBASE_ENDPOINT=ci.kbase.us \
ORCID_CLIENT_ID=${ORCID_CLIENT_ID} \
ORCID_CLIENT_SECRET=${ORCID_CLIENT_SECRET} \
MONGO_USERNAME=${MONGO_USERNAME} \
MONGO_PASSWORD=${MONGO_PASSWORD} \
DEV=yes \
docker compose -f docker-compose-dev.yml run orcidlink bash