KBASE_ENDPOINT=${KBASE_ENDPOINT} \
ORCID_CLIENT_ID=${ORCID_CLIENT_ID} \
ORCID_CLIENT_SECRET=${ORCID_CLIENT_SECRET} \
MONGO_USERNAME=${MONGO_USERNAME} \
MONGO_PASSWORD=${MONGO_PASSWORD} \
docker compose -f docker-compose-dev.yml up