KBASE_ENDPOINT=ci.kbase.us \
KBASE_SECURE_CONFIG_PARAM_ORCID_CLIENT_ID=${ORCID_CLIENT_ID} \
KBASE_SECURE_CONFIG_PARAM_ORCID_CLIENT_SECRET=${ORCID_CLIENT_SECRET} \
KBASE_SECURE_CONFIG_PARAM_MONGO_USERNAME=${MONGO_USERNAME} \
KBASE_SECURE_CONFIG_PARAM_MONGO_PASSWORD=${MONGO_PASSWORD} \
DEV=yes \
docker compose run orcidlink bash